In [1]:
import pandas as pd
# import the pandas library

In [12]:
df = pd.DataFrame(
   {
      "Name": [
         "S, Joseph",
         "P, Marlon",
         "J, Bryan",
         "P, Lisbeth",
         "M, Chris",
         "T, Ludwin",
      ],
      "Age": [0, 19, 20, 21, 20, 21],
      "Height": [6.2, 5.8, 5.6, 5.3, 5.10, 5.3],
      "Sex": ["male", "male", "male", "female", "male", "male"]
   }
)
# DataFrames have columns, and a label for each column. They also have 0-indexed
# rows, and these indices can be accessed in different ways. This is manual instantiation.
# When using a Python dictionary of lists, keys = column headers, and the values
# in each list as the columns

print(df)
# Each column in a DataFrame is a Series

         Name  Age  Height     Sex
0   S, Joseph    0     6.2    male
1   P, Marlon   19     5.8    male
2    J, Bryan   20     5.6    male
3  P, Lisbeth   21     5.3  female
4    M, Chris   20     5.1    male
5   T, Ludwin   21     5.3    male

In [10]:
# Print only the age column of the existing DataFrame; these columns are each 
# Pandas Series. A Series has a name and a data type, so you aren't able to 
# make a Series with multiple data types. If there are multiple data types in 
# a Series, Pandas will resolve this by trying to make them all the same data type.
# If they are numerical (int and float), all will change to float. If not, 
# they will be of object type.
print(df["Age"])

0     0
1    19
2    20
3    21
4    20
5    21
Name: Age, dtype: int64

In [11]:
# A Pandas Series
my_heights = pd.Series([12,2,4,23,40], name = "Heights")
print(my_heights)

0    12
1     2
2     4
3    23
4    40
Name: Heights, dtype: int64

In [13]:
# DataFrames are two-dimensional data structures that can store
# data of different types (characters, floating point values)
# in columns. It's similar to a spreadsheet, or a SQL table.

# Each column in a DataFrame is a Series
print(df["Age"])

0     0
1    19
2    20
3    21
4    20
5    21
Name: Age, dtype: int64

In [16]:
# Get the maximum age of the Age Series
print(df["Age"].max())

21

In [15]:
my_heights.max()

np.int64(40)

In [22]:
# Pandas provies methods that can be applied to DataFrames
# or Series. For example, the describe() method shows 
# basic numerical data of a column. It can display the stats 
# of an individual Series, or the numerical stats of the 
# columns of a DataFrame. This method returns a Pandas DataFrame or 
# Series, depending on the number of columns returned.
df.describe()

             Age    Height
count   6.000000  6.000000
mean   16.833333  5.550000
std     8.280499  0.403733
min     0.000000  5.100000
25%    19.250000  5.300000
50%    20.000000  5.450000
75%    20.750000  5.750000
max    21.000000  6.200000

In [23]:
# How to read and write tabular data
#
# Pandas has the read_csv() function to read data 
# stored in a csv. Pandas supports many file formats to read,
# including excel, sql, json, parquet, all beginning with 
# read_*, depending on what extension is being read.

titanic = pd.read_csv("titanic.csv")
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [24]:
# To see the first 8 rows:
titanic.head(8)
# The .head(N) method is used to see the first N rows of a
# DataFrame, from the top down, of the data (not including the column headers)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [25]:
# The .tail(N) method returns the last N rows of the DataFrame / Series it is called on.

titanic.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
# We can check on how pandas interpreted each of the column 
# data types by requesting the pandas dtypes attributes:

titanic.dtypes

# We can see that the data types in this DataFrame are integers
# (int64), floats (float64), and strings (object)

# No parentheses are used to get a Series or DataFrame dtypes,
# because dtypes is an attribute of both. We are only returning the specific
# attribute dtypes, by accessing it directly on the object. We needed the
# parentheses on the previous method, because the previous method is defined as a function
# that takes an action, e.g. getting the maximum numerical value from a DataFrame / Series

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object